version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install "poetry==2.0.1"
      # Add the export plugin
      - poetry self add poetry-plugin-export
      # Export the requirements.txt file
      - poetry export --with docs -f requirements.txt --output requirements.txt
      # Install from requirements.txt
      - pip install -r requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub
