[tool.poetry]
name = "spectrally constrained ica"
version = "0.1.0"
description = "An algorithmic implementation of FastICA with a spectral constraint."
authors = ["RyanBalshaw <ryanbalshaw81@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/RyanBalshaw/scICA"
repository = "https://github.com/RyanBalshaw/scICA"
keywords = ["Independent component analysis", "spectral constraints", "ICA", "single channel"]

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.1"
matplotlib = "^3.5.2"
scipy = "^1.8.1"
scikit-learn = "^1.1.2"
tqdm = "^4.64.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"
black = "^23.3.0"
isort = "^5.12.0"
interrogate = "^1.5.0"
pytest = "^7.3.1"
ruff = "^0.0.263"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
issues = "https://github.com/RyanBalshaw/scICA/issues"
